mod 'puppet/nginx', '1.0.0'
mod 'puppetlabs/stdlib'
mod 'puppetlabs/concat'
mod 'puppetlabs/translate'
mod 'puppetlabs/apt'
mod 'puppetlabs/reboot'
mod 'samuelson/dockeragent'
mod 'puppetlabs/docker'
mod 'saz-ssh', '6.2.0'
